name: Security Audit
on: [push, pull_request] # execute audit tasks on push or pull request
jobs:
    audit:
        name: Security Audit
        runs-on: ubuntu-latest # execute on lastest version of ubuntu
        env:
            DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
        steps:
            - name: Checkout
              uses: actions/checkout@v4 # up our application code

            - name: Setup PHP
              uses: shivammathur/setup-php@v2 # setup php + version + composer
              with:
                  php-version: 8.3
                  tools: composer:v2

            - name: Setup Cache # setup cache
              run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

            - name: Caching deps
              uses: actions/cache@v4
              with:
                  path: ${{ env.COMPOSER_CACHE_DIR }}
                  key: php8.3-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: |
                      php8.3-composer-latest-

            - name: Update composer
              run: composer self-update

            - name: install deps
              run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            - name: security audit
              run: |
                  composer audit \
                    --no-dev \
                    --abandoned="report" \
                    --ignore-severity="low" \
                    --ignore-severity="medium" \
                    --format="json" \
                    --no-ansi \
                    > /tmp/security-audit.json

            - name: upload security audit report # Artefact for upload audit json on github
              uses: actions/upload-artifact@v4
              if: always() # This step always execute
              with:
                  name: security-audit
                  path: /tmp/security-audit.json
