name: Quality Analysis
on: [push, pull_request]
jobs:
    quality:
        name: Quality Analysis
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.3
                  tools: composer:v2

            - name: Setup Cache
              run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

            - name: Caching deps
              uses: actions/cache@v4
              with:
                  path: ${{ env.COMPOSER_CACHE_DIR }}
                  key: php8.3-composer-${{ hashFiles('**/composer.json') }}
                  restore-keys: |
                      php8.3-composer-latest-

            - name: Update composer
              run: composer self-update

            - name: install deps
              run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --ansi

            - name: Quality analysis
              run: composer app:code-quality
